databases:
  - name: task_db_i1m5
    plan: free
    databaseName: task_db_i1m5
    user: matt_felpeto

services:
  - type: web
    plan: free
    name: task
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn taskOnline.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task_db_i1m5
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4